# amount of replica more than 1 will brin 409 error for telegram bots
replicaCount: 1

# Container option and values
image:
  repository: samandar278/streetfood-bot  # docker-image in docker hub
  tag: latest  # image teg (can be fixed for stability, example sha)
  pullPolicy: IfNotPresent  # policy of downloading image (local, if it is exist)

# Telegram token via argo cd parameters(sefest way)
bot:
  telegramToken: "CHANGE_ME_IN_ARGO_CD"

# Env empty couse token will be teken sefly from Secret (templates/secret.yaml)
env: []

# secrets for pull image from private repo (dont need for public image)
imagePullSecrets: []

# redefining a chart name (should be empty we dont need it)
nameOverride: ""
fullnameOverride: ""

# ServiceAccount for production (will be created autamaticly, less permissions)
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# annotations and labels for the pod (can be added for manitoring)
podAnnotations: {}
podLabels: {}

# Security context for production and also containers (security, empty by defult)
podSecurityContext: {}
securityContext: {}

# reresources for the container (CPU/RAM) — lightweight, so that the bot works stably even on a weak cluster
resources:
  limits:
    cpu: 200m   # MAX CPU
    memory: 256Mi  # MAX RAM
  requests:
    cpu: 100m   # garanted CPU
    memory: 128Mi  # garanted памяти

# autoscaling (HPA) — disabled, not needed for the polling bot (may cause a 409 error)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Node selector, tolerations, affinity — for placement on specific nodes (not needed for a local cluster)
nodeSelector: {}
tolerations: []
affinity: {}

#Additional volumes and mounts (for credentials.json or other secrets—we'll add them later if needed)
volumes: []
volumeMounts: []

service:
  type: ClusterIP
  port: 8000