apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-bot-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-bot-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "my-bot-chart.serviceAccountName" . }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}

          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-bot-chart.fullname" . }}
                  key: TELEGRAM_TOKEN

          volumeMounts:
            - name: google-credentials
              mountPath: /app/credentials.json
              subPath: credentials.json
              readOnly: true

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: google-credentials
          secret:
            secretName: telegram-bot-credentials
