apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-bot-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-bot-chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "my-bot-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-bot-chart.fullname" . }}-secret
                  key: TELEGRAM_TOKEN
            - name: GOOGLE_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: {{ include "my-bot-chart.fullname" . }}-secret
                  key: credentials.json
          volumeMounts:
            - name: credentials-volume
              mountPath: /app/credentials.json
              subPath: credentials.json
              readOnly: true
      volumes:
        - name: credentials-volume
          secret:
            secretName: {{ include "my-bot-chart.fullname" . }}-secret
