apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-bot-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "/metrics"
      labels:
        {{- include "my-bot-chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "my-bot-chart.serviceAccountName" . }}
      volumes:
        - name: credentials-volume
          secret:
            secretName: telegram-bot-credentials
            items:
              - key: credentials.json
                path: credentials.json
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
              protocol: TCP
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegrambot-my-bot-chart-secret
                  key: TELEGRAM_TOKEN
            - name: GOOGLE_CREDENTIALS_JSON
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-credentials
                  key: credentials.json
          volumeMounts:
            - name: credentials-volume
              mountPath: /app/credentials.json
              subPath: credentials.json
              readOnly: true
          resources:
            {{- with .Values.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
