apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "my-bot-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.metrics.port }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
