apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 80
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "my-bot-chart.selectorLabels" . | nindent 4 }}
