apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 8000
    targetPort: 8000
  selector:
    {{- include "my-bot-chart.selectorLabels" . | nindent 4 }}